### ISSUE TITLE
Having some troubles.  

### ISSUE THREAD

**Issue by JimmymaDdness** [gbnegrini/startrek-enterprise-revell-model#1]
Good day!  I read your whole post on the build;  Incredible work!

I am having some issues with getting this to work for some reason.   The code compiles fine but when I run the sketch, I just get the phasers and torpedoes sound on loop.   Even if I unplug all the inputs from the switches to the Arduino I get the phasers and torpedoes sounds.   Pushing the buttons does not play the requested mp3.   Also, where did you wire the 'Mute' switch to?

Thank you

Edit:  I was able to get it working by adding a voltage divider to the input of the Tx.  I am having a difficult time adding a couple of buttons for a couple of extra sounds though.

**Comment by JimmymaDdness** [comment]
Figured it out.   Added a pull-up resistor to the inputs as mine were still floating a little.

**Comment by gbnegrini** [comment]
@JimmymaDdness, sorry, I've just seen your comment!
I'm glad you manage to work this out. It has been ages since I've touched this project, and all the model build is stuck.
Best of luck! :vulcan_salute:

**Comment by JimmymaDdness** [comment]
No worries! I added your edited code to my Github.

**Comment by gbnegrini** [comment]
Awesome, I'll sure use it when I resume my model build.
